### ISSUE TITLE
[bug] version becomes unset when patch not found

### ISSUE THREAD

**Issue by bsara** [afs/rdf-delta#105]
I'm running into what seems to be a race condition where one server makes updates to the DB, RDF delta picks them up, the other Fuseki servers try to fetch the new changes, but a null patch is returned and it is seen as "not found". This isn't so much of an issue, the real issue is that whenever this happens the current version of the Fuseki server gets unset, which prevents any patches from being fetched in the future without manually updating the zone state file on the Fuseki servers.

I would expect that if a patch can't be found, that fact would be logged (as it is right now) and the current patch version would remain unchanged so that if the patch does exist in the future, it can be retrieved.

Looking through the code, this block seems to be the culprit: https://github.com/afs/rdf-delta/blob/a03c61bb54f2dbb766ec7925e3a8784faff98984/rdf-delta-client/src/main/java/org/seaborne/delta/client/DeltaConnection.java#L411-L436
Specifically the fact that on line 413 the default previous patch version is made to be "unset", then in the block that checks if the patch retrieved is null or not (lines 421-425), the original previous patch version is never restored, causing it to become unset. It seems that this would also happen if the delta server is down or can't be hit for some reason (as indicated by the catch block).

**Comment by afs** [comment]
Is it just one patch behind?

Remind me - what is your setup? Are you using S3 as the patch storage? and where do you have load balances in the system? (it all affects which delta client to talking to which delat server.)

The patch should have been written before the published version number is incremented in the server. 

So on first inspection, the only way the patch is not there is if S3 has not fully replicated the patch yet and its reading vai a different patch server so S3 read-after-write is not guaranteed.

If this is the situation, then the code quoted needs to be more defensive.

**Comment by afs** [comment]
Ping! There are a couple of questions above that would be useful to have answers for because the PR is fixing something I can see might happen, but that doesn't mean it is what you saw.

Also - are you deploying across regions? S3 eventual consistency shows up more there, AIUI.

**Comment by bsara** [comment]
> Is it just one patch behind?

not always, sometimes it is more

---

> Are you using S3 as the patch storage?

yes

---

> where do you have load balances in the system?

We only have one instance of the delta server running right now, but multiple zookeepers and 2 fuseki instances.

---

I'm also seeing this occur with a dataset that is not read-only, in no time at all, it is now behind by near 1000 patches.

**Comment by afs** [comment]
Fixed by #106.

**Comment by bsara** [comment]
@afs thanks soooo much for the quick turn around on this. When could there be a release for this fix?

**Comment by afs** [comment]
As soon as practical.

**Comment by afs** [comment]
Release done!
