### ISSUE TITLE
Patch conflict

### ISSUE THREAD

**Issue by tomkxy** [afs/rdf-delta#154]
We are running a HA setup with 3 Fuseki servers. Fuseki 4.3.2, rdf-delta: 1.1.0

We are facing a patch conflict error. From the logs it seems that a specific patch log version (306209) version is not found (extract from log file attached).  I am wondering how such a case, can happen and what options do we have to somehow fix that without having to wipe everything?

[t.log](https://github.com/afs/rdf-delta/files/8890773/t.log)

**Comment by afs** [comment]
Hi @tomkxy 

I don't recognize the situation. Could I ask for some more background to help investigate:

Have there been any earlier occurences of errors or warnings?

Is it on all the Fuseki servers or just one?
Does the error go away eventually? One possibility is S3 not propagating which occasion can take a longer time than normal. The code is supposed to cope.

Is your set up using multi-region or multi-availability zones?

Are all the Fuseki servers the target for updates?
Do you have some more of the log file before the extract , say the 10-20 previous requests?

**Comment by tomkxy** [comment]
Hi @afs, 
thanks for your fast reply. Highly appreciated!!!!
I am trying to answer some of the questions. 

The Fuseki servers and patch servers are running in a Kubernetes cluster. Pods are spread across different availability zones in the same region.
The error did not go away. We were resolving the issue by eventually creating a patch record manually. Here is the summary from our DevOps collegue:
 ```

Fuseki did not found a patch with version number: 306209
Latest patch we could find and verify was 306208.
We have appended a new patch, which became version 306210.
Patch 306210 had a "prev <uuid:d1173ee5-1d6b-4610-8e19-752a91a74494> "
We searched this UUID in the blob storage where the patch files are stored, we had no results.
So, we have created a new patch file, put the UUID: d1173ee5-1d6b-4610-8e19-752a91a74494 as the id, and used the UUID of patch 306208 as prev UUID.
Uploaded to the patch files blob storage.
Restarted the Zookeeper. 
```

We have 3 Fuseki instances and three patch servers running in the Kubernetes cluster. The patch servers are using minio blob storage. The setup is depicted in the attached graphic. ![Bildschirmfoto 2022-06-15 um 10 14 38](https://user-images.githubusercontent.com/1093609/173850730-7569d624-36d1-4bee-8b39-634bdf0f34f6.png)

Regarding logs: I attached the Fuseki logs:
[fuseki1.log](https://github.com/afs/rdf-delta/files/8910238/fuseki1.log)
[fuseki2.log](https://github.com/afs/rdf-delta/files/8910239/fuseki2.log)
[fuseki3.log](https://github.com/afs/rdf-delta/files/8910240/fuseki3.log)

For the patch server logs and any previous logs I need to came back, since the collegues need to pull them together and due to a public holiday tomorrow, I can only provide them on Friday.

**Comment by tomkxy** [comment]
Added the patch server logs (called zookeeper-n). At 10:55 UTC we experience the missing patch issue. The zookeeper logs show warnings and around 10:41 for the instance 0 and 1, at around 10:50 for instance 2
[fuseki-zookeeper-2.csv](https://github.com/afs/rdf-delta/files/8939118/fuseki-zookeeper-2.csv)
[fuseki-zookeeper-0.csv](https://github.com/afs/rdf-delta/files/8939120/fuseki-zookeeper-0.csv)
[fuseki-zookeeper-1.csv](https://github.com/afs/rdf-delta/files/8939123/fuseki-zookeeper-1.csv)

**Comment by tomkxy** [comment]
Hi @afs , 
we had the same issue again. I have saved the patchlog server logs. I see there a couple of issues which I cannot make sense of.
[zookeeper0.log](https://github.com/afs/rdf-delta/files/8955260/zookeeper0.log)
[zookeeper1.log](https://github.com/afs/rdf-delta/files/8955261/zookeeper1.log)
[zookeeper2.log](https://github.com/afs/rdf-delta/files/8955263/zookeeper2.log)
Would be highly appreciated, if you could have a look. I somehow, have the suspicion that we have an issue in our setup.

**Comment by afs** [comment]
Hi @tomkxy,

Working on these sorts of issues needs a chunk of time which I haven't managed to find yet. £job etc. Sorry about the delay. It will take awhile to extract key points from the log files.

Are the "fuseki-zookeeper" logs the patch server? And the same machines logged in `zookeeper*`?

The start of each `zookeeper*` seems to show some cluster problem. If there is a configuration error and the zookeeper cluster is not a cluster but a collection of single instances then that may cause problems but I can't think how that immediately connects to the problem of a missing patch.

Delays propagating should resolve themselves, possibly with a rejected update but if you are encountering a permanent fault which looks to tbe the case, then it is as if Minio lost something. (But I find that hard to believe.) None of this is geo-replicated?

If there is a configuration error, and the zookeeper cluster is not a cluster but a collection of single instances then that will cause problems to show if a Fuseki server or a patch server swaps over to using another Zookeeper instance but it does not explain what you are seeing. Generally, machines use the same server all the time and only failures and possibly internal load balancing cause it to show. The problem can remain dormant for quite some time.

**Comment by tomkxy** [comment]
Hi @afs, 

I appreciate very much your effort you put into that matter.
Yes, you are right, the fuseki-zookeeper are the patchlog servers. 

I am not sure, I understand this point:
> if there is a configuration error and the zookeeper cluster is not a cluster but a collection of single instances then that may cause problems but I can't think how that immediately connects to the problem of a missing patch.

As far as I am aware of the zookeeper nodes are just single instances running in the Kubernetes cluster most probably on different pods. Would I see it from the patchlog server config whether the zookeepers are forming a cluster?

No, we have no geo-replication. All pods are running in the same Azure region. 

> If there is a configuration error, and the zookeeper cluster is not a cluster but a collection of single instances then that will cause problems to show if a Fuseki server or a patch server swaps over to using another Zookeeper instance

Can you give me some hint how what I need to look for? 

In general, what makes me wonder is whether the config is right: the zookeepers are sitting behind a load balancer.

**Comment by afs** [comment]
@tomkxy 

Looks like there are three times a missing patch occurs - once in `fuseki-zookeeper` "version=306209" (by the way fuseki-zookeeper-2 does not overlap with fuseki-zookeeper-0, fuseki-zookeeper-1). 

"version=85869" which is the head of the log reported ion zookeeper*.log at about [2022-06-21 13:55:14] 
So it ought to exist.

"version=85817"` which is a long way back in the patch log from a previous run.

In all cases, there is no logged "append" and there is a significant about zookeeper warning (possible connectivity `issues).`  zookeeper* logs have zookeeper warning from the start.

But 85869 does seem to reappear - at least appends 85870 onwards though: (grepped for ver;85870):

```
zookeeper0.log:[2022-06-22 06:48:03] Patch      INFO  [191408] Patch:append ds:id:d6cda2 patch:id:c2b077 => ver=ver:85870
zookeeper0.log:[2022-06-22 06:48:44] Patch      INFO  [191701] Patch:fetch Dest=id:d6cda2, Patch=ver:85870
zookeeper0.log:[2022-06-22 06:56:04] Patch      INFO  [194739] Patch:fetch Dest=id:d6cda2, Patch=ver:85870
zookeeper0.log:[2022-06-22 06:56:48] Patch      INFO  [194952] Patch:fetch Dest=id:d6cda2, Patch=ver:85870
zookeeper1.log:[2022-06-22 06:56:35] Patch      INFO  [75141] Patch:fetch Dest=id:d6cda2, Patch=ver:85870
```
there are more fetches than Fuseki servers.

The repeated failures are possibly a Fuseki server trying to sync, it does look sometimes a server is a long way behind. It tries to get all the patches, fails and tries again and fails, etc etc.

Suggestions:
* The network reports from zookeeper need explaining. Even if everything works, they would mean periods of no update.
* Check the system configuration and especially that servers (Fuseki, patch log server , or zookeepers) are not sharing any file system.

**Comment by tomkxy** [comment]
@afs Thanks for putting the effort into the analysis. One more question what do you mean by:
`zookeeper-2 does not overlap with fuseki-zookeeper-0, fuseki-zookeeper-1)`?

**Comment by afs** [comment]
"fuseki-zookeeper-2" is a different time period to "fuseki-zookeeper-0" and "fuseki-zookeeper-1".

fuseki-zookeeper-0: 
ZK warnings from "6/13/2022, 10:45:54.767 AM
Log ends   "6/13/2022, 10:51:14.771 AM

fuseki-zookeeper-1:
ZK warnings from "6/13/2022, 10:39:41.866 AM,"
Log end    "6/13/2022, 10:45:21.339 AM

fuseki-zookeeper-2:
Starts "6/13/2022, 10:45:44.150 AM

**Comment by afs** [comment]
Hi @tomkxy -- I've been out of circulation for a bit and I'm getting back to outstanding issues.

Did you find out anything about the zookeeper setup?

Would it be useful to have a version of RDF Delta with additional logging? If so, what information might help?

**Comment by tomkxy** [comment]
Hi @afs,

thanks for getting back to me. We are still struggling with the issue. My colleagues already made some changes, but the issue still occur. I will check with my DevOps colleagues about additional logging. Will also try to collect what changes we made.

**Comment by tomkxy** [comment]
Hi @afs ,

regarding logging it is really hard to tell what we would need to see. We still see the communication issues of the patchlog servers and we made the decision to move the whole Fuseki setup to a dedicated nodepool which hopefully stabilizes the issues.

I would like to have a brief discussion with you regarding whether and how you might support us (paid). I appreciated, if you get in touch with me at thomas.krebs@t-systems.com .

**Comment by afs** [comment]
Sorry for the delay.

One S3 bucket is normal. The zookeeper cluster coordinates the naming.

**Comment by tomkxy** [comment]
Hi @afs , what do you mean with naming??? 

- Zones are separate but have same name
- Our patch log servers are sitting behind a load balancer. Fusekis are configured with the address of the patch log load balancer

**Comment by afs** [comment]
Naming: the patch get written to an S3 bucket with a object name that is globally unique (it's based on a UUID and the zookeeper indexes make sure there is one and only one name per patch). The patch store bucket is only a store of patches by their name - nothing to do with the indexes is stored there. Even if there is overlap of Delta clusters, patches won't be overwritten.

**Comment by afs** [comment]
> the zookeepers are sitting behind a load balancer.

Is there a load balancer between patch servers and the zookeeper machines?

Load balancer: I found this and while it is 2015 it refers to version 3.4.6 and RDF Delta uses 3.6.1 (release 2020) which comes indirectly via the latest Apache Curator). Zookeeper itself is 3.8.0 (2022). The versions are close so unlikely to have significant protocol changes.

https://stackoverflow.com/questions/30905007/load-balancer-with-zookeeper

It says the load balancer can interfere with the client switching over handoff because there isn't a zookeeper-client connection back through the LB.

I'm not saying it it the problem here but it does look like the right area.

What is the connection string in the patch servers configuration to connect to Zookeeper?

**Comment by tomkxy** [comment]
That is how the Fusekis are configured (each of them running in a different pod, so having its own Zone file)

```
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
 
## Example RDF Delta + Fuseki configuration.
 
PREFIX :        <http://base/#>
PREFIX fuseki:  <http://jena.apache.org/fuseki#>
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ja:      <http://jena.hpl.hp.com/2005/11/Assembler#>
PREFIX delta:   <http://jena.apache.org/rdf-delta#>
PREFIX tdb:     <http://jena.hpl.hp.com/2008/tdb#>
 
[] rdf:type fuseki:Server ;
.
 
<#service1> rdf:type fuseki:Service ;
    rdfs:label                         "TDB connectorData";
    fuseki:name                        "connectorData" ;
    fuseki:serviceQuery                "query" , "sparql" ;
    fuseki:serviceQuery                "query" ;
    fuseki:serviceUpdate               "update" ;
    fuseki:serviceUpload               "upload" ;
    fuseki:serviceReadWriteGraphStore  "data" ;
    fuseki:serviceReadGraphStore       "get" ;
    fuseki:dataset                     <#dataset> ;
    .
 
<#dataset> rdf:type delta:DeltaDataset ;
    delta:changes  "http://our-fuseki-zookeeper-cluster:1071/" ;
    delta:patchlog "PATCHLOG" ;
    delta:zone "Zone" ;
    delta:storage "tdb2" ;


```
Patchlog server config (script starting the patchlog server); each patchlog server is running on separate kubernetes pod

The S3 endpoint evaluates to a Minio endpoint in our Kubernetes cluster which mimicking the S3 bucket.

```
#!/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0
 
## Run a RDF Delta Patch Log Server
## This is the common script run from within directories zk1, zk2 and zk3.
 
ID=$(hostname | awk -F'-' '{print $NF+1}')
echo $ID > ./customconfig/zookeeper/ZkData/myid
echo "My Cluster ID is $ID"
CONNECT="our-fuseki-zookeeper-0.our-fuseki-zookeeper-headless:2181,our-fuseki-zookeeper-1.our-fuseki-zookeeper-headless:2181,our-fuseki-zookeeper-2.our-fuseki-zookeeper-headless:2181"
PORT="1071"
 
echo "Run Delta Patch Server : id = $ID : port = $PORT"
echo "Connect server string: $CONNECT"
 
echo "AWS storage bucket name: $AWS_ACCESS_KEY_ID"
 
sed -ie "s|{SED_AWS_ACCESS_KEY_ID}|$AWS_ACCESS_KEY_ID|" customconfig/s3config/awskeys
sed -ie "s|{SED_AWS_SECRET_ACCESS_KEY}|$AWS_SECRET_ACCESS_KEY|" customconfig/s3config/awskeys
 
cat customconfig/s3config/awskeys
 
if [[ -e "/app/jvmargs" ]]
then
    JVM_ARGS_ADDED=`cat jvmargs`
    JVM_ARGS+=$JVM_ARGS_ADDED
    echo $JVM_ARGS
fi
 
java $JVM_ARGS -Djute.maxbuffer=10485760 -jar /app/delta-server.jar --port "$PORT" --zk="$CONNECT" --zkCfg=./customconfig/zookeeper/zoo.cfg --s3endpoint="$S3ENDPOINT" --s3Bucket=$S3BUCKET --s3Region=us-ea
st-1 --s3Keys=customconfig/s3config/awskeys
```

**Comment by tomkxy** [comment]
Hi @afs ,
as an update. After removing the load balancer in front of the Zookeepers, our installation has stabilized. Anyway , I would still appreciated a glance on our configuration as posted above.

**Comment by afs** [comment]
I'm glad to hear the system has stabilized.

The configuration, Fuseki setup and the setting of `CONNECT`, looks OK.

Unrelated: `cat customconfig/s3config/awskeys` will leak the keys to the log files.
