### ISSUE TITLE
Example to start

### ISSUE THREAD

**Issue by charbull** [afs/rdf-delta#2]
Hello,

This is super interesting ! is there any example to start?

Thank you,
Charbel

**Comment by afs** [comment]
Not really any yet - there are the tests.

What sort of usage are you interested in? The patch format? Ways to use the patch format for publishing? For high availability?

**Comment by charbull** [comment]
Hello,
My use case is the following:
My gateways push their topology in RDF format. 
Their topology information contains localisation of sensors, measurements, and how they communicate with each others.
When someone changes a sensor for various reasons, or place it in a new location, the gateway regenerates the rdf and sends it to my remote server. 
So I have no way of knowing what really changed. I would like to use your work to detect the changes that occurred on my gateway.

Is this possible?

**Comment by afs** [comment]
Yes, that sound possible. rdf-delta provides tools to capture changes as they happen to data (it's comparing two datasets after changes have happened). As the changes happen, which means all adds and deletes of triples, quads, and prefixes, an RDF patch file, which is a transaction log, is created. 

While the patch format and protocol are system neutral, the integration tools is with Apache Jena. You set up a dataset for the data with a wrapper around it to capture the changes including the case for Fuseki (assembler provided - no codeing necessary).

**Comment by charbull** [comment]
This is what I am looking for :)

Are you planning to write some documentation to start with the topic? or maybe you already have a paper or any doc?

Thank

**Comment by afs** [comment]
Hopefully soon, the web site will have examples.

Your use case sounds like either:

1. a local dataset being changed, and changes sent to a SPARQL server.
1. a local dataset being changed, and changes sent to patch log server, where changes can be picked up by several other applications, including a SPARQL server but other kinds of applications.

**Comment by charbull** [comment]
That's great ! looking forward to it !

**Comment by afs** [comment]
Examples: [rdf-delta-examples in the GH repo](https://github.com/afs/rdf-delta/tree/master/rdf-delta-examples) such as [DeltaEx2_DatasetCollectPatch](https://github.com/afs/rdf-delta/blob/master/rdf-delta-examples/src/main/java/org/seaborne/delta/examples/DeltaEx2_DatasetCollectPatch.java) that collects and print changes.
 
There is a specific [page about replicated Fuseki servers](https://afs.github.io/rdf-delta/ha-fuseki.html) which is keeping two datasets sync'ed.

Hope that helps,

**Comment by charbull** [comment]
@afs Thank you !
Is it possible to use ref-delta server with just SPAxRQL endpoints without a Fueski server? 
https://afs.github.io/rdf-delta/ha-fuseki.html

Thx

**Comment by afs** [comment]
A Delta server works in patches. Something needs to send out the patch.

It possible (in theory - the code isn't currently active) to have any standard SPARQL Update endpoint updated from a patch server, caveat that blank nodes across changes can't be handled.

**Comment by afs** [comment]
Closing because [there are examples](https://github.com/afs/rdf-delta/tree/master/rdf-delta-examples).
