### ISSUE TITLE
RDF Delta distribution link is not accessible

### ISSUE THREAD

**Issue by xsfang** [afs/rdf-delta#49]
this link can not be accessed:

http://central.maven.org/maven2/org/seaborne/rdf-delta/rdf-delta-dist

**Comment by akuckartz** [comment]
Is that really http and not https ?

**Comment by xsfang** [comment]
neither http nor https works. :)

**Comment by afs** [comment]
https://repo1.maven.org/maven2/org/seaborne/rdf-delta/

Nowadays, only "https://repo1.maven.org/" workf foe accessing the central maven repository. This change happened when they starts enforcing https. The error message you will be getting says that "central.maven.org" is not a DNS name.

"http://central.maven.org/" no longer works for any maven artifacts of any system 

The RDF Delta docs need changing to reflect this.

**Comment by afs** [comment]
Done with commit https://github.com/afs/rdf-delta/commit/ea869f223b979051b12d69842d12dfcb749f6449
