### ISSUE TITLE
shiro.ini file is ignored by Fuseki server

### ISSUE THREAD

**Issue by bsara** [afs/rdf-delta#58]
The Fuseki server seems to be ignoring a `shiro.ini` file placed in `FUSEKI_BASE`. Should it be expected to be used or is there a different way to secure the Fuseki endpoints with the rdf-delta fuseki?

**Comment by afs** [comment]
Shiro support is used in Fuseki/Full.

For Fuseki/main, which RDF Delta uses, has support for user authentication using the Jetty features [Fuseki/main access control](https://jena.apache.org/documentation/fuseki2/fuseki-data-access-control.html) to give control on server, datasets, endpoint and per-graph levels.

Is there something specific from Shiro you were looking for?

(It is possible to use Shiro with Fuseki/main to get user authentication but it needs Java code - see [ExFusekiMain_2_AddShiro.java](https://github.com/apache/jena/blob/main/jena-fuseki2/jena-fuseki-main/src/test/java/org/apache/jena/fuseki/main/examples/ExFusekiMain_2_AddShiro.java)0.

**Comment by bsara** [comment]
I just need to secure some of the endpoints. I don't have a preference on how that is done so long as I know how to do it.

**Comment by afs** [comment]
Then the Jetty-based control (see link) is easier.
