### ISSUE TITLE
Unable to generate patches from existing TDB triple store

### ISSUE THREAD

**Issue by wwelling** [afs/rdf-delta#8]
This may as well be my ignorance of how to implement. I am trying to integrate rdf-delta patch server with [Vitro](https://github.com/vivo-project/Vitro). I would like for the patch server to either start from the [VIVO](https://github.com/vivo-project/VIVO), the running application on top of Vitro, or start independently from it. I am able to start the `DeltaServer` create a `DataLink` and `Zone`, but I am unable to have a `DeltaClient` populate patch logs from the applications TDB triplestore. 

Here is the latest attempt:

```Java
RDFServiceFactory rdfServiceFactory = contentTripleSource.getRDFServiceFactory();
RDFService rdfService = rdfServiceFactory.getRDFService();
RDFServiceGraph defaultGraph = new RDFServiceGraph(rdfService);
Dataset dataset = contentTripleSource.getDataset();
DatasetGraph datasetGraph = dataset.asDatasetGraph();


FileOps.ensureDir("DeltaServer");
FileOps.clearAll("DeltaServer");
FileOps.ensureDir("Zone");
FileOps.clearAll("Zone");
DeltaServer server = DeltaServer.server(1066, "DeltaServer");
try {
    server.start();
}catch (BindException ex) {
    System.err.println("Can't start the patch log server: " + ex.getMessage());
    System.exit(1);
}

DeltaLink dLink = DeltaLinkHTTP.connect("http://localhost:1066/");
Zone zone = Zone.connect("Zone");

Id dsRef = dLink.newDataSource("Vitro", "http://scholars/Vitro");

DeltaClient deltaClient = DeltaClient.create(zone, dLink);

deltaClient.connectExt(dsRef, datasetGraph, SyncPolicy.TXN_RW);


long ldx1 = Txn.calculateRead(datasetGraph, () -> Iter.count(datasetGraph.find()));
// initial count
System.out.println("\n\n\n\n" + ldx1 + "\n\n\n\n");

ChangeSet changeSet = rdfService.manufactureChangeSet();
Triple triple = new Triple(NodeFactory.createURI("http://localhost:9000/vivo/scholars"), NodeFactory.createURI("http://www.w3.org/2000/01/rdf-schema#label"), NodeFactory.createLiteral("Hello, World!"));
changeSet.addAddition(new ByteArrayInputStream(sparqlTriple(triple).getBytes()), ModelSerializationFormat.N3, defaultGraph.getGraphURI());
// This is how triplestore changes are performed throughout the application
try {
    rdfService.changeSetUpdate(changeSet);
} catch (RDFServiceException e1) {
    e1.printStackTrace();
}

// Direct attempts

Quad quad = SSE.parseQuad("(_ :s :p :o)");

System.out.println("\n\n\n\n\n\n");
long dx1 = Txn.calculateRead(datasetGraph, () -> Iter.count(datasetGraph.find()));
// no change
System.out.println("\n\n\n\n" + dx1 + "\n\n\n\n");
Txn.executeWrite(datasetGraph, ()->datasetGraph.add(quad));
Txn.executeWrite(datasetGraph,()->RDFDataMgr.read(datasetGraph, "data.ttl"));
long dx2 = Txn.calculateRead(datasetGraph, () -> Iter.count(datasetGraph.find()));
// no change
System.out.println("\n\n\n\n" + dx2 + "\n\n\n\n");
System.out.println("\n\n\n\n\n\n");

try (DeltaConnection dConn = deltaClient.get(dsRef)) {
    DatasetGraph dsg = dConn.getDatasetGraph();
    long x0 = Txn.calculateRead(dsg, () -> Iter.count(dsg.find()));
    System.out.println("\n\n\n\n" + x0 + "\n\n\n\n");
    Txn.executeWrite(dsg, ()->dsg.add(quad));
    Txn.executeWrite(dsg,()->RDFDataMgr.read(dsg, "data.ttl"));
    long x1 = Txn.calculateRead(dsg, () -> Iter.count(dsg.find()));
    // no change
    System.out.println("\n\n\n\n" + x1 + "\n\n\n\n");
    Version ver = dConn.getLocalVersion();
    RDFPatch patch1 = dConn.getLink().fetch(dsRef, ver);
    // null, never created
    System.out.println("\n\n\n\n" + patch1 + "\n\n\n\n");
    RDFPatchOps.write(System.out, patch1);
} catch (Exception e) {
    e.printStackTrace();
}
```

I have had many iterations with no luck. I simply have to be missing something.

**Comment by afs** [comment]
Hi there,

What the app needs to do it "attach" the dataset to the delat client and then "connect" - these are normally combined into a "register" operation but that's missing for the external case in the releases.

"connectExt" does not work properly; it'll get removed and there will be a "registerExternal"

The way to set (v0.7.0) is:

```
        deltaClient.attachExternal(dsRef, datasetGraph);
        deltaClient.connect(dsRef, SyncPolicy.TXN_RW);
```

The code below worked for me with v 0.7.0, taking out your local code:
```
    public static void main(String[] args) {
        DatasetGraph datasetGraph = DatasetGraphFactory.createTxnMem();
        FileOps.ensureDir("DeltaServer");
        FileOps.clearAll("DeltaServer");
        FileOps.ensureDir("Zone");
        FileOps.clearAll("Zone");
        DeltaServer server = DeltaServer.server(1066, "DeltaServer");
        try {
            server.start();
        }catch (BindException ex) {
            System.err.println("Can't start the patch log server: " + ex.getMessage());
            System.exit(1);
        }

        DeltaLink dLink = DeltaLinkHTTP.connect("http://localhost:1066/");
        Zone zone = Zone.connect("Zone");

        Id dsRef = dLink.newDataSource("Vitro", "http://scholars/Vitro");

        DeltaClient deltaClient = DeltaClient.create(zone, dLink);
        deltaClient.attachExternal(dsRef, datasetGraph);
        deltaClient.connect(dsRef, SyncPolicy.TXN_RW);
// Will become:
//      deltaClient.registerExternal(dsRef, datasetGraph, SyncPolicy.TXN_RW);

        Quad quad = SSE.parseQuad("(_ :s :p :o)");

        try (DeltaConnection dConn = deltaClient.get(dsRef)) {
            DatasetGraph dsg = dConn.getDatasetGraph();
            long x0 = Txn.calculateRead(dsg, () -> Iter.count(dsg.find()));
            System.out.println("Size: " + x0);
            Txn.executeWrite(dsg, ()->dsg.add(quad));
            //Txn.executeWrite(dsg,()->RDFDataMgr.read(dsg, "data.ttl"));
            long x1 = Txn.calculateRead(dsg, () -> Iter.count(dsg.find()));
            // no change
            System.out.println("Size: " + x1);
            Version ver = dConn.getLocalVersion();
            RDFPatch patch1 = dConn.getLink().fetch(dsRef, ver);
            // null, never created

            System.out.println(patch1);
            RDFPatchOps.write(System.out, patch1);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.exit(0);
    }
```

**Comment by wwelling** [comment]
I can confirm that did work with a freshly created DatasetGraph. Unfortunately, it did not work with the applications existing Dataset.

First concern is that it cleared out the dataset, which the comments in code state. Is that ideal? Would the Dataset have to be repopulated after each reconnect to the delta server? Secondly, it did not execute the writes after when connected with the delta client. Which lead to the patch not being created.

Is there a way to connect a Dataset and not clear it out? Can you think of any reason why the applications existing Dataset is not compatible with the client?

**Comment by wwelling** [comment]
Is the DeltaClient compatible with an SDB triplestore?

**Comment by afs** [comment]
Delta wraps an existing datasets to add the patch capture abnd synchronization That's why you use the dataset from the DeltaConnection. It works with any storage - SDB included. (With SDB, the database can be shared anyway  because multiple apps can access it over JDBC.)

**Comment by afs** [comment]
@wwelling - what you say "did not work" what are you expecting to happen? Delta does not sync an existing dataset - it captures changes made afterwards.

In your initial example, you add the quad, setup delta and add the same quad.

In the variant below, a quad added then Delta setup then a different quad added: there is one quad in the patch.
Output:
```
Size: 1
Size: 2
Local version: ver:1
H id <uuid:98e33824-3344-4a48-992b-25c88d71751a> .
TX .
A <http://example/s> <http://example/p> <http://example/o> .
TC .
```

from:

```
    public static void main(String[] args) {
        DatasetGraph datasetGraph = DatasetGraphFactory.createTxnMem();
        Quad quad1 = SSE.parseQuad("(_ :s :p :1)");
        Txn.executeWrite(datasetGraph,()->datasetGraph.add(quad1));

        FileOps.ensureDir("DeltaServer");
        FileOps.clearAll("DeltaServer");
        FileOps.ensureDir("Zone");
        FileOps.clearAll("Zone");
        DeltaServer server = DeltaServer.server(1066, "DeltaServer");
        try {
            server.start();
        }catch (BindException ex) {
            System.err.println("Can't start the patch log server: " + ex.getMessage());
            System.exit(1);
        }

        DeltaLink dLink = DeltaLinkHTTP.connect("http://localhost:1066/");
        Zone zone = Zone.connect("Zone");

        Id dsRef = dLink.newDataSource("Vitro", "http://scholars/Vitro");

        DeltaClient deltaClient = DeltaClient.create(zone, dLink);
        deltaClient.attachExternal(dsRef, datasetGraph);
        deltaClient.connect(dsRef, SyncPolicy.TXN_RW);

        Quad quad2 = SSE.parseQuad("(_ :s :p :o)");

        try (DeltaConnection dConn = deltaClient.get(dsRef)) {
            DatasetGraph dsg = dConn.getDatasetGraph();
            long x0 = Txn.calculateRead(dsg, () -> Iter.count(dsg.find()));
            System.out.println("Size: " + x0);
            Txn.executeWrite(dsg, ()->dsg.add(quad2));

            long x1 = Txn.calculateRead(dsg, () -> Iter.count(dsg.find()));
            System.out.println("Size: " + x1);
            Version ver = dConn.getLocalVersion();
            System.out.println("Local version: "+ver);
            RDFPatch patch1 = dConn.getLink().fetch(dsRef, ver);
            if ( patch1 == null )
                System.out.println("no patch");
            else
                RDFPatchOps.write(System.out, patch1);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.exit(0);
    }
```

**Comment by wwelling** [comment]
I don’t expect it to synchronize anything. I am not claiming it does not work, simply I am unable to get it to work in the context I would like it to. What happened is that it cleared out the dataset and disallowed adding. I actually think the results I am getting are do to how the datasets are managed in the application I am attempting to integrate. Since, I have experimented more and have had different results.

Does the the external dataset get modified after connect? https://github.com/afs/rdf-delta/blob/master/rdf-delta-client/src/main/java/org/seaborne/delta/client/DeltaClient.java#L290

How would I listen/subscribe to the patch logs from another client? Or does it require polling?

As I said, it does work as per the examples, but those all create a new dataset. The issue was a question regarding existing datasets.

**Comment by afs** [comment]
The example has a pre-existing dataset - it's just convenience to create in the example itself. It can be any dataset.

> The {@code DatasetGraph} is assumed to empty and is brought up-to-date.

This refers to attaching to an existing log which already has patches.  When "attach" happens and there is no preexisting delta state, it is assumed to be at version 0. Existing data is left alone. If the log in the patch server is ahead at say version 5, patches 1 to 5 will be applied locally.

After setup, `SyncPolicy` of the DeltaClient controls when sync happens. `TXN_RW`, sync at the start of every transaction, `TXN_W`, sync at the start of a write transaction, `NONE`, no automatic sync, the app needs to do it.

If the external datasets has data, then on the other client system, it had better be the same initial state. Existing data is not synchronized automatically.

Example of two datasets, one patch log server:

https://github.com/afs/rdf-delta/blob/master/rdf-delta-examples/src/main/java/org/seaborne/delta/examples/DeltaEx7_TwoDatasetsPatchLogServer.java

That everything is in one program is convenience - there are two client zones which are unrelated.

**Comment by afs** [comment]
SDB usage - the only use case I can see is for recording patched but not synchronization. With SDB, high availability is a feature of the SQL database setup. IRC SDB does not work properly with `Txn` because `Txn` is not a JDBC-transaction.

**Comment by wwelling** [comment]
Thank you for the clarification. I am closing this as I have all the information needed to proceed.

I will let you know how it goes. FYI, the goal of this integration is to attempt near real-time synchronization of a Solr index mapped from a triplestore.

**Comment by wwelling** [comment]
Finally was able to produce patches from the Vitro applications dataset. Turns out the dataset was buried in several wrapping services. Anyhow, publishing the patches works great. Thanks again for the responses. 

I am now going to attempt consuming the patches from another application. Is there a prescribed way to subscribe to the patch server?

**Comment by wwelling** [comment]
I am able to poll patch logs from another application. So far by current version, min version, max version, and latest patch by id. Is there a way to poll for all patches after a timestamp? 

Subscribing to a producer would be ideal. Do you think it may be able to run patch log server in application performing to synchronize Solr index and have the application managing the triplestore simple a DeltaClient creating patches to the remote DeltaServer?

**Comment by afs** [comment]
I've just added an example of a polling client -- [DeltaEx10_PollingClient](https://github.com/afs/rdf-delta/blob/master/rdf-delta-examples/src/main/java/org/seaborne/delta/examples/DeltaEx10_PollingClient.java)

Timestamps are hard in a distributed system - it uses version number, keeping a local copy of last version processed by the client.

There is not a built-in subscription mechanism. It is complicated for the server to track which clients to push to, which clients are currently active, and which patches each client has successfully processed (just delivering a patch isn't enough). It is better to use a proper message bus system, which may already be available in the deployment environment.

In the example, like RSS/Atom, clients check for changes. That can be done on a separate thread to turn it into a local event-driven application.

**Comment by wwelling** [comment]
I did not know the versions can be incremented like that. Neat. We can use a polling mechanism on a schedule for now. We may eventually setup a message broker. Thanks again.

**Comment by wwelling** [comment]
Is it possible to reattach dataset to DeltaClient from an SDB dataset that is connected and disconnected frequently?

**Comment by afs** [comment]
It would only be needed if the dataset object became invalid. Just because the JDBC connection connects/disconnects doesn't invalid the Dataset object (IIRC).

The easiest is probably to create a new DelatClient but you could create a switching one. TDB2's `DatasetGraphSwitchable` does that.

**Comment by wwelling** [comment]
Unfortunately, the dataset is closing. Would require major changes to properly handle the sdb datasets in Vitro. I am going to focus on Vitro tdb rdf-delta support for now. Thanks again.
